/* eslint-disable camelcase */
export const DS_GLAccountType = [
  { id: 'Balance Sheet Account', name: 'Balance Sheet Account' },
  { id: 'Non Operating Expense or Income', name: 'Non Operating Expense or Income' },
  { id: 'Primary Cost or Revenue', name: 'Primary Cost or Revenue' },
  { id: 'Secondary Cost', name: 'Secondary Cost' },
];

export const DS_GLAccountGroup = [
  { id: 'Aktiva', name: 'Aktiva' },
  { id: 'Beban Admiistrasi dan Umum', name: 'Beban Admiistrasi dan Umum' },
  { id: 'Beban Lainnya', name: 'Beban Lainnya' },
  { id: 'Beban Penjualan', name: 'Beban Penjualan' },
  { id: 'COGS', name: 'COGS' },
  { id: 'Conversion Account', name: 'Conversion Account' },
  { id: 'Kewajiban & Ekuitas', name: 'Kewajiban & Ekuitas' },
  { id: 'Pendapatan Lainnya', name: 'Pendapatan Lainnya' },
  { id: 'Penjualan', name: 'Penjualan' },
  { id: 'Secondary', name: 'Secondary' },
];

export const DS_GLStatusGroup = [
  { id: 'CH67', name: 'Reconciliation Accts with Contract Ref.' },
  { id: 'G001', name: 'General (with text, assignment)' },
  { id: 'G003', name: 'Material consumption accounts' },
  { id: 'G004', name: 'Cost accounts' },
  { id: 'G005', name: 'Bank accounts (obligatory value date)' },
  { id: 'G006', name: 'Material accounts' },
  { id: 'G007', name: 'Asset accts (w/o accumulated depreciatn)' },
  { id: 'G008', name: 'Assets area clearing accounts' },
  { id: 'G009', name: 'Bank accounts (obligatory due date)' },
  { id: 'G011', name: 'Clearing accounts (with settlement per.)' },
  { id: 'G012', name: 'Receivables/payables clearing' },
  { id: 'G013', name: 'General (obligatory text)' },
  { id: 'G014', name: 'MM adjustment accounts' },
  { id: 'G017', name: 'Freight/customs provisions/clearing (MM)' },
  { id: 'G018', name: 'Scrapping (MM)' },
  { id: 'G019', name: 'Other receivables/payables' },
  { id: 'G023', name: 'Plant maintenance accounts' },
  { id: 'G025', name: 'Inventory adjustment accounts' },
  { id: 'G026', name: 'Accounts for down payments made' },
  { id: 'G029', name: 'Revenue accounts' },
  { id: 'G030', name: 'Change in stock accounts' },
  { id: 'G031', name: 'Accounts for down payments received' },
  { id: 'G032', name: 'Bank accounts (obligat.value/due dates)' },
  { id: 'G033', name: 'Cost accounts for external services' },
  { id: 'G036', name: 'Revenue accts (with cost center)' },
  { id: 'G039', name: 'Accts for pmnts on acct made for assets' },
  { id: 'G040', name: 'Personnel clearing accounts' },
  { id: 'G041', name: 'Tax office clearing accounts' },
  { id: 'G045', name: 'Goods/invoice received clearing accounts' },
  { id: 'G049', name: 'Manufacturing costs accounts' },
  { id: 'G050', name: 'Central control clearing accounts' },
  { id: 'G052', name: 'Accounts for fixed asset retirement' },
  { id: 'G056', name: 'Amortization accounts' },
  { id: 'G059', name: 'Inventory accounting material stock acct' },
  { id: 'G062', name: 'Investment support accounts' },
  { id: 'G064', name: 'Other cost accounts (obligatory text)' },
  { id: 'G067', name: 'Reconciliation accounts' },
  { id: 'G068', name: 'Reconciliatn accts (payables - Austria)' },
  { id: 'G069', name: 'Cost accounts (travel expenses)' },
  { id: 'G070', name: 'Clearing accounts (travel expenses)' },
  { id: 'G071', name: 'Reconcil.accts (KIDNO/foreign payment)' },
  { id: 'ICCF', name: 'CO <-> FI reconciliation posting' },
  { id: 'SECC', name: 'SECC' },
  { id: 'Z067', name: 'Reconciliation accounts (Paym Ref. Mand)' },
];
